// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
/**
 * 示例问候命令。
 */
async greet(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 从磁盘加载用户偏好设置。
 * 文件不存在时返回默认偏好设置。
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 将用户偏好设置保存到磁盘。
 * 使用临时文件加重命名的原子写入方式，避免文件损坏。
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 发送一条系统原生通知。
 * 移动端暂不支持通知，因此会返回错误。
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 将紧急数据保存为 JSON 文件，便于稍后恢复。
 * 校验文件名，并强制执行 10MB 大小限制。
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 从之前保存的 JSON 文件加载紧急数据。
 * 文件不存在时返回 FileNotFound。
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 删除超过 7 天的恢复文件。
 * 返回已删除文件数量。
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 获取日志目录路径，方便用户定位崩溃日志。
 */
async getLogDir() : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_log_dir") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 追加一条前端或后端崩溃日志。
 */
async appendCrashLog(source: string, message: string, stack: string | null, context: JsonValue | null) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("append_crash_log", { source, message, stack, context }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 从磁盘加载构建队列预设。
 * 文件不存在时返回空集合。
 */
async loadBuildQueuePresets() : Promise<Result<BuildQueuePresetStore, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_build_queue_presets") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * 将构建队列预设保存到磁盘。
 * 使用临时文件加重命名的原子写入方式。
 */
async saveBuildQueuePresets(store: BuildQueuePresetStore) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_build_queue_presets", { store }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async detectEnvironment() : Promise<Result<EnvironmentReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("detect_environment") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveSdkVersions(request: BuildRequest) : Promise<Result<SdkResolution[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_sdk_versions", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listSdkVersions() : Promise<Result<SdkVersionOption[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_sdk_versions") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadSdkSources() : Promise<Result<SdkSourceConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_sdk_sources") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSdkRootConfig(config: SdkRootConfig) : Promise<Result<SdkSourceConfig, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_sdk_root_config", { config }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async autoConfigureSdkSources() : Promise<Result<SdkAutoConfigReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("auto_configure_sdk_sources") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async inspectSdkSetup() : Promise<Result<SdkSetupReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("inspect_sdk_setup") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async configureRequiredSdks(config: SdkRootConfig, refresh: boolean) : Promise<Result<SdkSetupReport, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("configure_required_sdks", { config, refresh }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveSdkSource(version: string, source: SdkSourceOverride) : Promise<Result<SdkVersionOption, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_sdk_source", { version, source }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeSdkSource(version: string) : Promise<Result<SdkVersionOption[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_sdk_source", { version }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startBuild(request: BuildRequest) : Promise<Result<BuildJobId, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_build", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelBuild(jobId: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_build", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async listArtifacts(jobId: string) : Promise<Result<BuildArtifact[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_artifacts", { jobId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openArtifactFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_artifact_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveBuildLog(path: string, contents: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_build_log", { path, contents }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * 会持久化到磁盘的应用偏好设置。
 * 仅包含跨会话需要保留的设置。
 */
export type AppPreferences = { theme: string; 
/**
 * 用户偏好的界面语言，例如 `zh-CN` 或 `en-US`。
 * 为 None 时根据系统语言自动选择。
 */
language: string | null }
export type BuildArtifact = { version: string | null; configuration: string | null; kind: string; path: string }
export type BuildConfiguration = "Debug" | "Release" | "Both"
export type BuildJobId = { id: string }
/**
 * 构建队列预设。
 */
export type BuildQueuePreset = { id: string; name: string; requests: BuildRequest[]; created_at: string }
/**
 * 构建队列预设集合。
 */
export type BuildQueuePresetStore = { presets: BuildQueuePreset[] }
export type BuildRequest = { plugin_root: string; module_name: string; package_name: string; versions: string[]; configuration: BuildConfiguration; sdk_source: SdkSourceMode; package_mode: PackageMode; zip_enabled: boolean; clean_output: boolean; refresh_sdk_cache: boolean; output_dir: string | null }
export type CompilerPlatform = "Windows" | "Macos" | "Linux" | "Unsupported"
export type EnvironmentReport = { os: string; supported: boolean; compiler_platform: CompilerPlatform; cmake_preset: string | null; binary_extension: string | null; cmake: ToolStatus; visual_studio: ToolStatus; windows_sdk: ToolStatus; xcode: ToolStatus; clang: ToolStatus; python: ToolStatus; installed_sdk_zips: InstalledSdkZip[]; installed_c4d_versions: InstalledC4dVersion[]; cache_root: string }
export type InstalledC4dVersion = { version: string; path: string; sdk_version: string; download_url: string }
export type InstalledSdkZip = { version: string; path: string; size_bytes: number }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type PackageMode = "Merged" | "PerVersion" | "Both"
/**
 * 恢复操作错误类型，供前端按类型匹配。
 */
export type RecoveryError = 
/**
 * 文件不存在，这是预期情况，不代表系统故障。
 */
{ type: "FileNotFound" } | 
/**
 * 文件名校验失败。
 */
{ type: "ValidationError"; message: string } | 
/**
 * 数据超过大小限制。
 */
{ type: "DataTooLarge"; max_bytes: number } | 
/**
 * 文件系统读写错误。
 */
{ type: "IoError"; message: string } | 
/**
 * JSON 序列化或反序列化错误。
 */
{ type: "ParseError"; message: string }
export type SdkAutoConfigReport = { sdk_root: string | null; installed_versions: InstalledC4dVersion[]; versions: SdkVersionOption[] }
export type SdkResolution = { version: string; source: SdkResolutionSource; sdk_root: string | null; archive_path: string | null; download_url: string | null; status: string }
export type SdkResolutionSource = "Config" | "InstalledZip" | "OfficialDownload" | "Cache"
export type SdkRootConfig = { sdk_root: string | null }
export type SdkSetupReport = { sdk_root: string | null; installed_versions: InstalledC4dVersion[]; versions: SdkVersionOption[]; prepared_versions: SdkResolution[]; requirements: SetupRequirement[]; summary: string }
export type SdkSourceConfig = { sdk_root: string | null }
export type SdkSourceMode = "ConfiguredThenInstalledThenOfficial"
export type SdkSourceOverride = { sdk_root: string | null; sdk_zip: string | null; download_url: string | null }
export type SdkVersionOption = { version: string; label: string; configured: boolean; sdk_root: string | null; sdk_zip: string | null; download_url: string | null; status: string }
export type SetupRequirement = { key: string; label: string; status: SetupRequirementStatus; detail: string; path: string | null; version: string | null; auto_installable: boolean; install_hint: string | null }
export type SetupRequirementStatus = "Ready" | "Warning" | "Missing" | "Manual"
export type ToolStatus = { found: boolean; path: string | null; version: string | null; message: string | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
