use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{compiler, notifications, preferences, recovery};

    Builder::<tauri::Wry>::new().commands(collect_commands![
        preferences::greet,
        preferences::load_preferences,
        preferences::save_preferences,
        notifications::send_native_notification,
        recovery::save_emergency_data,
        recovery::load_emergency_data,
        recovery::cleanup_old_recovery_files,
        compiler::detect_environment,
        compiler::resolve_sdk_versions,
        compiler::list_sdk_versions,
        compiler::load_sdk_sources,
        compiler::save_sdk_root_config,
        compiler::auto_configure_sdk_sources,
        compiler::inspect_sdk_setup,
        compiler::configure_required_sdks,
        compiler::save_sdk_source,
        compiler::remove_sdk_source,
        compiler::start_build,
        compiler::cancel_build,
        compiler::list_artifacts,
        compiler::open_artifact_folder,
        compiler::save_build_log,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
pub fn export_ts_bindings() -> Result<(), String> {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .map_err(|error| format!("Failed to export TypeScript bindings: {error}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings().expect("Failed to export TypeScript bindings");
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
